/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Event;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeSelectionModel;
import sun.reflect.generics.tree.Tree;

/**
 *
 * @author Alex Nelson
 */

//IMPLEMENT EXIT FUNCTION
//CANT SEEM TO PROPERLY IMPLEMENT OPTIONPANE
//USING PALETTE
public class PanelA1 extends javax.swing.JFrame {

    private List<JLabel> jLabList; //List containing references to jLabels
    private Point pointStart;//Interim variable for drawing CompositionElements
    private Point pointEnd;//Interim variable for drawing CompositionElements
    private SerializableComposite serComField;//Serializable class containing array of geometric primitives and base image
    private List<DefaultMutableTreeNode> nodeList;//List of all the nodes referring to JLabels in the sidebar 
   private DefaultMutableTreeNode rootNode;//variable used in side menu
   private DefaultTreeModel treeModel;//variable used in side menu
//Used as interface for saving and opening
    /**
     * Creates new form NewJFrame
     */
    public PanelA1() {
        initComponents();
        initUserGen();
        
    }
private void initUserGen(){// Custom initlialization code
    
    rootNode = new DefaultMutableTreeNode("Root Node");
    treeModel = new DefaultTreeModel(rootNode);
treeModel.addTreeModelListener(new ElementsTreeListener());

ElementsTree = new JTree(treeModel);
    ElementsTree.setEditable(true);
ElementsTree.getSelectionModel().setSelectionMode
        (TreeSelectionModel.DISCONTIGUOUS_TREE_SELECTION);
ElementsTree.setShowsRootHandles(true);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        ElementsTree = new javax.swing.JTree();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        New = new javax.swing.JMenuItem();
        createCustom = new javax.swing.JMenu();
        DrawL = new javax.swing.JMenuItem();
        DrawR = new javax.swing.JMenuItem();
        DrawCustom = new javax.swing.JMenuItem();
        CreateCustom = new javax.swing.JMenuItem();

        fileChooser.setDialogTitle("This is my open dialog");
        fileChooser.setFileFilter(new MyCustomFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(ElementsTree);

        jSplitPane1.setLeftComponent(jScrollPane1);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jLayeredPane1);

        jMenu3.setText("File");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        Open.setText(" Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        jMenu3.add(Open);

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jMenu3.add(Save);

        New.setText("New");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });
        jMenu3.add(New);

        jMenuBar2.add(jMenu3);

        createCustom.setText("Edit");
        createCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCustomActionPerformed(evt);
            }
        });

        DrawL.setText("Draw Line");
        DrawL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrawLActionPerformed(evt);
            }
        });
        createCustom.add(DrawL);

        DrawR.setText("Draw Rect");
        DrawR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrawRActionPerformed(evt);
            }
        });
        createCustom.add(DrawR);

        DrawCustom.setText("Draw Custom");
        DrawCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrawCustomActionPerformed(evt);
            }
        });
        createCustom.add(DrawCustom);

        CreateCustom.setText("Create Custom");
        createCustom.add(CreateCustom);

        jMenuBar2.add(createCustom);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        //Opens and deserializes image/composition composite placing
        //it in the CompositeLabel label1 in the JPanel
        int returnVal = fileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        
     serComField=(new SerializableComReader(file)).getSerCom();
        
        
        try {
            
            jLabList.add(new ImageJLab(serComField.getImage()));
            for(int i=0; i<serComField.getLines().size(); i++) {
                
                jLabList.add(serComField.getLines().get(i));
            jLayeredPane1.add(jLabList.get(jLabList.size()-1));
            }
            
          
        }catch (Exception ex) {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }
    } else {
        System.out.println("File access cancelled by user.");
    }
    }//GEN-LAST:event_OpenActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        fileChooser.showSaveDialog(this);//PUT IN TRY STATEMENT FOR Headless EXCEPTION??
            
    }//GEN-LAST:event_SaveActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    // LOOK INTO DIFFERENT APPROACHES TO ADDING AND REMOVING MOUSELISTENERS
    //Code for Drawing Line
    private void DrawLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrawLActionPerformed
        //SORT OUT NEW ITEM FIRST
        MouseAdapter ml=new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    pointStart = e.getPoint();
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    pointEnd = e.getPoint();
                }};
        jLayeredPane1.addMouseListener(ml);
        double[] xp={pointStart.getX(), pointEnd.getX()};
        double[] yp={pointStart.getY(), pointEnd.getY()};
        initializeCEJLab(new GeneralTracing(xp, yp));
        
                jLayeredPane1.removeMouseListener (ml);
    }//GEN-LAST:event_DrawLActionPerformed

    private void DrawRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrawRActionPerformed
        MouseAdapter ml=new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    pointStart = e.getPoint();
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    pointEnd = e.getPoint();
                }};        jLayeredPane1.addMouseListener(ml);
        double[] xp={pointStart.getX(), pointEnd.getX(), pointStart.getX(), pointEnd.getX()};
        double[] yp={pointStart.getY(), pointEnd.getY(),pointStart.getY(), pointEnd.getY()};
        initializeCEJLab(new GeneralTracing(xp, yp));
    }//GEN-LAST:event_DrawRActionPerformed

    private void DrawCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrawCustomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrawCustomActionPerformed

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        int result=JOptionPane.showConfirmDialog(this, //THIS?
    "Any unsaved progress will be deleted. "
    + "Do you wish to continue?","Create New",
    JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(result==JOptionPane.OK_OPTION){
            jLayeredPane1.removeAll();
            jLabList.clear();
            this.setTitle("New Composition"); //MAY BE INADVISABLE
        serComField.clearSerCom();
        }
        else{
        //Do Nothing
    }
    }//GEN-LAST:event_NewActionPerformed

    private void createCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCustomActionPerformed
        
    }//GEN-LAST:event_createCustomActionPerformed
//Creates and draws a ComElemJLab component, adding mouseListener etc
    private void initializeCEJLab(GeneralTracing ce){
    serComField.addElement(ce);//TRY CLAUSE??
        jLabList.add(ce);
jLabList.get(jLabList.size()).addMouseListener(new MouseAdapter(){
     @Override
     public void mousePressed(MouseEvent e) {
        maybeShowPopup(e);
    }

     @Override
    public void mouseReleased(MouseEvent e) {
        maybeShowPopup(e);
    }

    private void maybeShowPopup(MouseEvent e) {
        if (e.isPopupTrigger()) {
            jPopupMenu1.show(e.getComponent(),
                       e.getX(), e.getY());
        }
    }
});
    jLayeredPane1.add(jLabList.get(jLabList.size()));
        
        
       
                
                (jLabList.get(jLabList.size()-1)).setOpaque(false);
                (jLabList.get(jLabList.size()-1)).repaint();
                
                //adds new node to the side menu
               nodeList.add(new DefaultMutableTreeNode("Element Number " + (Integer.toString(nodeList.size()))));
                rootNode.add(nodeList.get(nodeList.size()-1));}

    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CreateCustom;
    private javax.swing.JMenuItem DrawCustom;
    private javax.swing.JMenuItem DrawL;
    private javax.swing.JMenuItem DrawR;
    private javax.swing.JTree ElementsTree;
    private javax.swing.JMenuItem New;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem Save;
    private javax.swing.JMenu createCustom;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}